apiVersion: v1
kind: Pod
metadata:
  name: myapp-stagging
  labels:
    environment: stagging
spec:
  containers:
  - name: myapp-stagging
    image: hoangduc02011998/go-pod:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
        protocol: TCP

--- 
apiVersion: v1
kind: Pod
metadata:
  name: myapp-uat
  labels:
    environment: uat
spec:
  containers:
  - name: myapp-uat
    image: hoangduc02011998/go-pod:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
        protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-production
  labels:
    environment: production
spec:
  containers:
  - name: myapp-production
    image: hoangduc02011998/go-pod:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
        protocol: TCP