apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the RC is processing on => 
    app: myapp-rc # label value => it must be equal label of the pod
  template: # pod template
    metadata:
      name: myapp-rc
      labels:
        app: myapp-rc
    spec:
      containers:
        - name: myapp-rc
          image: hoangduc02011998/go-pod:latest
          ports:
            - containerPort: 8081
              protocol: TCP
