apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-rs
  template:
    metadata:
      labels:
        app: app-rs
    spec:
      containers:
      - name: app-rs
        image: hoangduc02011998/go-pod:latest
        ports:
          - containerPort: 8081
            protocol: TCP

