apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pv
rules:
  - verbs:
      - "list"
      - "get"
    apiGroups:
      - ""
    resources:
      - "persistentvolumes"