apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-redis
  template:
    metadata:
      labels:
        app: myapp-redis
    spec:
      containers:
      - name: myapp-redis
        image: hoangduc02011998/go-pod:run-redis
        ports:
          - containerPort: 8081
            protocol: TCP