apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-file
spec:
  containers:
  - name: pod-secret-file
    image: hoangduc02011998/go-pod:secret-file
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081
        protocol: TCP
    volumeMounts:
      - mountPath: /secrets/env-secret.yaml
        name: secret-volume
        subPath: env-secret.yaml
      - mountPath: /configs/env.yaml
        subPath: env.yaml
        name: config-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-file
        items:
          - key: env-secret.yaml
            path: env-secret.yaml
    - name: config-volume
      configMap:
        name: cm-file
        items:
          - key: env.yaml
            path: env.yaml
