apiVersion: v1
kind: Secret
metadata:
  name: secret-file
type: Opaque
data:
  env-secret.yaml: |-
    cmVkaXMtc2VjcmV0OgogIHVzZXItc2VjcmV0OiByZWRpc191c2VyCiAgcGFzc3dvcmQtc2VjcmV0OiByZWRpc19wYXNzd29yZAo=
  
